<html>
<head>
    <title>Sign In</title>
</head>
<body>
<form method="post" action="signin">
    <center><h1>Sign In</h1>
        <p><a href="/signup">Sign Up</a> </p>
        <p>e-mail:</p>
        <input type="email" name="email"/>
        <p>password:</p>
        <input type="password" name="password"/>
        <p>
            <input type="submit" id="btn">
        </p></center>
</form>
</body>
</html>